### ISSUE TITLE
API  requests are ignored until assets are installed. Please, wailt  

### ISSUE THREAD

**Issue by GuanMinjie** [snipking/cordova-hot-code-push#2]
error code :   -18 ; 
ASSETS_FOLDER_IS_NOT_YET_INSTALLE

what's mean?  

When cordova build is executed - www content is copied to the platform-specific www folder:

For Android: platforms/android/assets/www.

but  I didn't get it;

Could you please help me?

**Comment by snipking** [comment]
Error code explanation: https://github.com/snipking/cordova-hot-code-push/wiki/Error-codes

And can you provide a working demo ?

**Comment by GuanMinjie** [comment]
hello, I think you can read Chinese. I can describe it clearly in Chinese.

**Comment by GuanMinjie** [comment]
sorry！ I find some problems, and I will reply to you after I solve them. Verifying these problems can solve some of my doubts。

**Comment by snipking** [comment]
好的
