### ISSUE TITLE
ios 初始化报错

### ISSUE THREAD

**Issue by GuanMinjie** [snipking/cordova-hot-code-push#4]
![屏幕快照 2019-10-14 下午3 25 22](https://user-images.githubusercontent.com/29447163/66734876-5ed4fd80-ee97-11e9-8ba5-952c85477e84.png)
报错
![屏幕快照 2019-10-14 下午3 26 26](https://user-images.githubusercontent.com/29447163/66734889-685e6580-ee97-11e9-99e1-b4f0c2786005.png)
报错函数

请问有遇到这种情况吗，我对ios开发不熟悉，请问这问题怎么解决

**Comment by snipking** [comment]
要看一下调用这个 URLByAppendingPathComponent 的时候传的参数是什么，第一个参数，可以加一个断点调试一下。

**Comment by GuanMinjie** [comment]
chcpJsonFileURLFromBundle	NSURL *	@"file:///private/var/containers/Bundle/Application/{path}/www/chcp.json"
![屏幕快照 2019-10-15 上午10 16 51](https://user-images.githubusercontent.com/29447163/66794769-2f74ce00-ef35-11e9-94e0-64265af5c641.png)

但是jsonData 的 返回 nil
导致后边进一步传参数的时候  URLByAppendingPathComponent 为nil

HCPApplicationConfig.m  函数所在文件

**Comment by snipking** [comment]
你打包的时候是不是没有做 `cordova-hcp build`

**Comment by GuanMinjie** [comment]
不好意思 是这样的 cordova-hcp build 我确实做了，cordova prepare ios 或者 cordova build ios 是正确的命令 可以将 www 文件夹拷贝到对应平台下的www 文件加下。
但是 我用的ionic 框架，执行 ionic cordova prepare ios  或者 ionic cordova build ios 命令时，会先删除www文件夹，然后重新生成www文件夹，导致原来生成的 chcp.json 不存在了。

这点是我忽略了的，正确使用命令后可以初始化  下载更新 安装更新 但是还是和 android情况一样，安装之后会白屏，不能跳转。

**Comment by snipking** [comment]
不确定是不是 ionic 的问题，是不是改了上下文配置？ios 读取和存储的路径也不对？我是用 cordova 测试的，没测过 ionic。你那里有可以提供的 demo 的话我可以调试看看。

**Comment by GuanMinjie** [comment]
https://gitlab.com/guanminjie/hcp-demo.git
您可以试一下

**Comment by snipking** [comment]
参考 https://github.com/snipking/cordova-hot-code-push/issues/3#issuecomment-571843773
