### ISSUE TITLE
Failed to download application configuration file

### ISSUE THREAD

**Issue by harisudangnanasegaran** [snipking/cordova-hot-code-push#5]
Successfully Install plugin and followed steps given by plugin, Unable to achieve not working hot code push www not updated failed to download

**Comment by snipking** [comment]
Any details ?

**Comment by harisudangnanasegaran** [comment]
while trying to invoke mobile application  I am getting this error "Failed to download application configuration file" . 
 final ApplicationConfig newAppConfig = downloadApplicationConfig(applicationConfigUrl);
        if (newAppConfig == null) {
            setErrorResult(ChcpError.FAILED_TO_DOWNLOAD_APPLICATION_CONFIG, null);
            return;
        }

**Comment by snipking** [comment]
Read the wiki [Cordova-config-preferences](https://github.com/snipking/cordova-hot-code-push/wiki/Cordova-config-preferences) and set config-file path in `config.xml`.

Use `cordova-hcp` cli to build `chcp.json` and `chcp.manifest`. [cordova-hot-code-push-cli](https://github.com/snipking/cordova-hot-code-push-cli)

Upload `chcp.json` to your server which path set in `config.xml`.
